all:

FILES= mcu/main_sw.c \
	mcu/main_swhw.c \
	fpga/src_filter/filter.cpp \
	fpga/src_filter/filter.h \
	fpga/src_filter/directives.tcl \
	build/med_filtr.bin \
	report.pdf
zip:
	zip xtisov00.zip $(FILES) 
